version: "3.1"
services:
  kubernetes-example01:
    privileged: true
    image: asia.gcr.io/dantrisoft/kubernetes-example01:0.0.1
    container_name: example01
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    # command: /server
    ports:
      - "3000:3000"
    expose:
      - 3000
    networks:
      - network-kubernetes-example

volumes:
  jenkins_data:
    driver: local

networks:
  network-kubernetes-example: