apiVersion: v1
kind: Service
metadata:
  name: kubernetes-example01-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    name: kubernetes-example01