
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/PeteProgrammer/go-automapper"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.16.16"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.0"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.2"

[[constraint]]
  name = "github.com/mongodb/mongo-go-driver"
  version = "0.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/paked/configure"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/zebresel-com/mongodm"
  version = "2.0.1"

[[constraint]]
  name = "gopkg.in/jeevatkm/go-model.v1"
  version = "1.1.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"
