host: 'localhost'
scheme: 'http'
servers:
  - name: "Server 1"
    scheme: "http"
    host: "localhost"
    port: "3001"
  - name: "Server 2"
    scheme: "http"
    host: "localhost"
    port: "3002"
  - name: "Server 3"
    scheme: "http"
    host: "localhost"
    port: "3003"